### ISSUE TITLE
Hardware interface

### ISSUE THREAD

**Issue by ekgerke** [kmalinich/node-bmw#6]
Hi.

What do you use in order to interface with the car? Skimmed through the source/documentation, wasn't able to find a definitive answer.

**Comment by kmalinich** [comment]
Personally I'm using Rolf Resler's USB IBUS interface:
http://www.reslers.de/IBUS/

You can also use a USB cable that is compatible with INPA/NCSexpert/etc, and connect the IBUS/KBUS line to pin OBD pin 7, as detailed at the end of the first post in this thread:

https://www.bimmerforums.com/forum/showthread.php?1505990-My-DIS-INPA-SSS-CARSOFT-NAVCODER-Interface

**Comment by ekgerke** [comment]
sweet. thank you for information. good work, btw.
